import AfrikaCountries from '@/components/africa/africa'
import React from 'react'

export const metadata = {
  title: "COUNTRYFY | AFRICA",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <AfrikaCountries/>
    </div>
  )
}
