import AsiaCountries from '@/components/asia/Asia'
import React from 'react'

export const metadata = {
  title: "COUNTRYFY | ASIA",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
        <AsiaCountries/>
    </div>
  )
}
