import EuropaCountries from '@/components/evropa/Evropa1'
import CountriesInfo from '@/components/evropa/Evropa1'
import React from 'react'

export const metadata = {
  title: "COUNTRYFY | EVROPA",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        <EuropaCountries/>
    </div>
  )
}
